// Order matches the cells of public/icons/ingredients-125.webp: 5 columns, 25 rows, read row by row.
// The icons were generated with Codex in five themed sheets of 25.
export const ingredientIcons = [
  // Basics
  "pasta", "herbs", "nuts", "cheese", "oil", "garlic", "tomato", "onion", "meat", "fish", "egg", "flour", "sugar", "spices", "milk",
  "butter", "lemon", "rice", "mushroom", "chili", "carrot", "water", "bread", "honey", "bowl",
  // Vegetables
  "potato", "bell-pepper", "cucumber", "zucchini", "eggplant", "broccoli", "cauliflower", "cabbage", "lettuce", "spinach", "corn", "peas",
  "beans", "chickpeas", "lentils", "beetroot", "pumpkin", "celery", "leek", "spring-onion", "radish", "asparagus", "avocado", "ginger", "olives",
  // Fruit, sweets and baking
  "apple", "banana", "strawberry", "raspberry", "blueberry", "cherry", "orange", "lime", "grapes", "pear", "peach", "mango", "pineapple",
  "coconut", "raisins", "chocolate", "cocoa", "vanilla", "jam", "maple-syrup", "yeast", "baking-powder", "whisk", "oats", "cake",
  // Meat, fish, dairy and pantry
  "drumstick", "bacon", "sausage", "ham", "mince", "shrimp", "salmon", "tuna", "tofu", "yogurt", "cream", "mozzarella", "feta", "cottage-cheese",
  "soy-sauce", "vinegar", "wine", "beer", "stock", "canned", "mustard", "ketchup", "tortilla", "noodles", "dumpling",
  // Herbs, spices, nuts and seeds
  "parsley", "dill", "rosemary", "thyme", "mint", "coriander", "chives", "bay-leaf", "nutmeg", "star-anise", "peppercorns", "paprika", "curry",
  "cinnamon", "cloves", "sesame", "poppy", "seeds", "almond", "walnut", "hazelnut", "peanut", "pine-nuts", "ice", "mortar",
] as const;
export type IngredientIcon = typeof ingredientIcons[number];

// Polish and English names are matched by word stems. Earlier rules win, so specific phrases come before the broader
// families they mention: "mąka ziemniaczana" is flour, "pestki dyni" are seeds, "masło orzechowe" is peanut.
const rules: [IngredientIcon, RegExp][] = [
  ["water", /(^|\s)(wod[aęyąo]|wrząt)|(^|\s)(boiling |cold |warm |hot )?water/],
  ["ice", /(^|\s)lód|(^|\s)lodu|kostk[aię] lodu|kruszon|ice cubes?|(^|\s)ice$/],
  ["stock", /bulion|wywar|rosoł|rosół|kostk[aię] rosołow|(^|\s)stock|broth|bouillon/],
  ["lime", /limonk|(^|\s)limes?(\s|$)/],
  ["lemon", /cytry|lemon/],
  ["orange", /pomarańcz|mandaryn|grejpfrut|(^|\s)oranges?(\s|$)|mandarin|grapefruit|clementine/],
  ["peanut", /masł[oa] orzechow|orze\S* ziemn|arachid|peanut/],
  ["butter", /masł|ghee|butter/],
  ["vinegar", /ocet|octu|balsamic|vinegar/],
  ["soy-sauce", /sojow|tamari|sos rybn|ostrygow|worcester|teriyaki|(^|\s)soy|fish sauce|oyster sauce/],
  ["oil", /oliw[aęyą]|olej|smalec|tłuszcz|(^|\s)oil|(^|\s)lard/],
  ["olives", /oliwk|oliwek|kapar|(^|\s)olives?(\s|$)|caper/],
  ["mustard", /musztard|majonez|chrzan|mustard|mayo|horseradish/],
  ["ketchup", /ketchup/],
  ["wine", /(^|\s)win(o|a|em|ie)?(\s|$)|wódk|(^|\s)rum(u|em)?(\s|$)|whisk(y|ey)|brandy|koniak|likier|amaretto|prosecco|marsal|porto|sherry|(^|\s)wine|vodka|cognac|liqueur/],
  ["beer", /(^|\s)piw|(^|\s)beer|(^|\s)(ale|lager)(\s|$)/],
  ["paprika", /papryk[aię]? (słodk|wędzon|ostr|mielon|w proszku)|papryki (słodkiej|wędzonej|ostrej|mielonej)|cayenne|chili (w proszku|mielon|w płatkach)|płatki chili|paprika|chil+i (powder|flakes)|pepper flakes/],
  ["peppercorns", /pieprz\S* (ziarnist|w ziarn)|ziarn\S* pieprzu|ziele angielskie|jałowc|jałowiec|peppercorn|allspice|juniper/],
  ["bell-pepper", /bell pepper|sweet pepper|capsicum|(red|green|yellow|orange) peppers?(\s|$)/],
  ["spices", /(^|\s)sól|(^|\s)soli(\s|$)|pieprz|(^|\s)salt|(^|\s)pepper(\s|$)|black pepper/],
  ["curry", /curry|kurkum|garam|kmin|kumin|kolendr\S* mielon|kardamon|ras el|za.?atar|imbir mielon|turmeric|cumin|cardamom|ground coriander|ground ginger/],
  ["cinnamon", /cynamon|cinnamon/],
  ["nutmeg", /gałk|nutmeg/],
  ["cloves", /goździk|^(whole |ground )?cloves?$/],
  ["star-anise", /anyż|badian|anise/],
  ["bay-leaf", /laurow|bay lea/],
  ["vanilla", /wanili|vanilla/],
  ["mortar", /przypraw|mieszank|seasoning|spice (mix|blend)/],
  ["chili", /chil+i|chile|jalape|papryczk|habanero|sriracha|tabasco|harissa/],
  ["bell-pepper", /papryk|(^|\s)peppers?(\s|$)/],
  ["spring-onion", /dymk|zielon\S* cebul|spring onion|green onion|scallion/],
  ["chives", /szczypior|chive/],
  ["garlic", /czosn|garlic/],
  ["leek", /(^|\s)por(a|u|em|y)?(\s|$)|leek/],
  ["onion", /cebul|szalot|onion|shallot/],
  ["tomato", /pomidor|passat|koncentrat|przecier|tomato/],
  ["noodles", /ramen|udon|(^|\s)soba|noodl|makaron\S* (ryżow|sojow|chiński|azjat)|chow mein/],
  ["dumpling", /pierog|(^|\s)uszk|raviol|tortellin|pielmien|gyoz|wonton|knedl|kopytk|gnocch|dumpling/],
  ["pasta", /makaron|spaghett|penne|tagliatell|fettuccin|lasagn|rigaton|fusill|farfall|linguin|klusk|orzo|świderk|kokardk|(^|\s)pasta|macaroni/],
  ["yeast", /drożdż|yeast/],
  ["baking-powder", /proszek do piecz|proszku do piecz|(^|\s)sod[ayę]|amoniak|żelatyn|agar|budyń|budyniu|kisiel|baking (powder|soda)|bicarbonate|gelatin|corn ?starch/],
  ["flour", /mąk|krupczatk|semolin|kasz[aęy] mann|skrobi|flour|starch/],
  ["tortilla", /tortill|wrap|(^|\s)pit[ay]?(\s|$)|nachos|lavash/],
  ["bread", /chleb|bułk|bagiet|grzank|pieczyw|(^|\s)tost|ciabat|bajgl|naan|panko|kajzerk|rogal|brioche|croissant|bread|(^|\s)buns?(\s|$)|baguette|toast|crouton|bagel|sourdough/],
  ["cake", /biszkopt|herbatnik|ciastk|ciast[oa] |(^|\s)bez[ya]?(\s|$)|kruche|spód|sponge|ladyfinger|savoiardi|biscuit|cookie|pastry|pie crust|meringue/],
  ["shrimp", /krewet|krab|homar|langust|owoce morza|małż|mule|kalmar|ośmiorni|shrimp|prawn|crab|lobster|mussel|clam|squid|octopus|scallop|seafood/],
  ["salmon", /łoso|pstrąg|salmon|trout/],
  ["tuna", /tuńczy|sardyn|szprot|anchois|tuna|sardine|anchov/],
  ["fish", /ryb|dorsz|śledź|śledzi|makrel|sandacz|mintaj|halibut|morszczuk|tilapi|okoń|karp|szczupak|flądr|fish|(^|\s)cod(\s|$)|haddock|mackerel|herring|sea bass/],
  ["cocoa", /kakao|(^|\s)kaw[aęy]|espresso|cocoa|coffee/],
  ["almond", /migdał|almond/],
  ["bacon", /boczek|boczku|bekon|pancett|guanciale|bacon/],
  ["sausage", /kiełbas|parówk|salami|chorizo|pepperoni|kabanos|frankfurt|metk|sausage|kielbasa/],
  ["ham", /szynk|prosciutto|baleron|wędlin|(^|\s)ham(\s|$)/],
  ["mince", /mięs\S* mielon|mielon\S* (wołow|wieprz|drob|z indyka|z kurczaka)|(^|\s)mielone(\s|$)|farsz|minced|ground (beef|pork|meat|lamb|turkey|chicken)|(^|\s)mince/],
  ["drumstick", /kurcza|kurczę|drób|drobi|indy|kacz|(^|\s)gęś|(^|\s)gęsi|udk|udzi|skrzyd|podudz|chicken|turkey|duck|wings?(\s|$)|thigh|drumstick|poultry/],
  ["meat", /wołow|wieprz|mięs|cielęc|jagnię|stek|antrykot|rostbef|polędwic|karkówk|schab|łopatk|żeberk|golonk|kotlet|wątróbk|beef|pork|steak|veal|lamb|meat|(^|\s)chops?(\s|$)|cutlet|loin|(^|\s)ribs?(\s|$)|brisket|liver/],
  ["tofu", /tofu|tempeh|seitan/],
  ["feta", /(^|\s)fet[aęy]|fecie|bryndz|halloumi|oscyp/],
  ["mozzarella", /mozzarel|burrat|bocconcin/],
  ["cottage-cheese", /twaróg|twarog|twarożk|serek wiejsk|ricott|homogeniz|mascarpon|serek śmietank|philadelph|cottage cheese|cream cheese|quark|(^|\s)curd/],
  ["cheese", /(^|\s)ser(\s|$|ek|a|y|em|u|ze)|parmez|gouda|cheddar|gorgonzol|pecorino|grana|camembert|brie|emmental|edam|gruy|cheese|parmigiano/],
  ["cream", /śmietan|crème|creme|mleczk\S* kokos|mlek\S* kokos|cream|coconut milk/],
  ["yogurt", /jogurt|skyr|kefir|maślank|zsiadł|yogh?urt|buttermilk/],
  ["milk", /mlek|mleczk|napój roślin|napoju roślin|milk/],
  ["egg", /jaj|żółtk|białk|(^|\s)eggs?|yolk/],
  ["chocolate", /czekolad|nutell|chocolate/],
  ["maple-syrup", /syrop|syrup/],
  ["honey", /miód|miod|honey/],
  ["jam", /dżem|konfitur|powidł|marmolad|frużelin|(^|\s)jam(\s|$)|jelly|preserve|marmalade/],
  ["sugar", /cukier|cukr|słodzik|erytryt|ksylit|stewi|sugar|sweetener/],
  ["oats", /płatk|owsian|musli|müsli|granol|otręb|(^|\s)oats?|oatmeal|cereal|flakes/],
  ["rice", /ryż|risotto|arborio|basmati|kasz|quinoa|komos|kuskus|bulgur|jęczmie|proso|amarantus|orkisz|(^|\s)rice|couscous|barley/],
  ["lentils", /soczewic|lentil/],
  ["chickpeas", /ciecierzyc|cieciork|hummus|chickpea|garbanzo/],
  ["beans", /fasol|(^|\s)bób|(^|\s)bobu|edamame|(^|\s)beans?(\s|$)/],
  ["peas", /groszek|groszk|groch|(^|\s)peas?(\s|$)/],
  ["corn", /kukurydz|(^|\s)corn(\s|$)/],
  ["seeds", /pestk|słonecznik|siemi|chia|(^|\s)len(\s|$)|lnian|seeds?(\s|$)|flax/],
  ["potato", /ziemniak|kartofl|batat|frytk|potato|(^|\s)fries/],
  ["beetroot", /burak|buracz|botwink|beet/],
  ["radish", /rzodkiew|rzodkiewk|radish/],
  ["parsley", /natk|pietruszk\S* (natk|liś)|parsley/],
  ["carrot", /marchew|marchw|marchewk|pietrusz|pasternak|włoszczyzn|warzyw|carrot|parsnip|vegetable|veggie/],
  ["celery", /seler|celery|celeriac/],
  ["zucchini", /cukini|zucchini|courgette/],
  ["eggplant", /bakłażan|oberżyn|eggplant|aubergine/],
  ["cucumber", /ogór|cucumber|pickle|gherkin/],
  ["broccoli", /brokuł|broccoli/],
  ["cauliflower", /kalafior|romanesco|cauliflower/],
  ["cabbage", /kapust|brukselk|kimchi|cabbage|sauerkraut|brussels/],
  ["lettuce", /sałat|rukol|roszponk|endywi|cykori|jarmuż|lettuce|arugula|rocket|(^|\s)kale|greens|romaine/],
  ["spinach", /szpinak|szczaw|pokrzyw|spinach|chard/],
  ["asparagus", /szparag|asparagus/],
  ["pumpkin", /dyni|dynia|pumpkin|squash/],
  ["avocado", /awokad|guacamol|avocado/],
  ["ginger", /imbir|galangal|ginger/],
  ["mushroom", /grzyb|pieczar|borowik|(^|\s)kurk[iaę]|shiitake|boczniak|podgrzyb|portobello|trufl|mushroom|truffle/],
  ["apple", /jabł|apple/],
  ["banana", /banan/],
  ["strawberry", /truskaw|poziomk|strawberr/],
  ["raspberry", /malin|jeżyn|raspberr|blackberr/],
  ["blueberry", /borówk|jagod|porzeczk|żurawin|blueberr|cranberr|currant/],
  ["cherry", /wiśn|czereś|cherr/],
  ["grapes", /winogron|grape/],
  ["raisins", /rodzyn|daktyl|suszon\S* (śliw|morel|fig|owoc)|raisin|(^|\s)dates?(\s|$)|prune|dried fruit/],
  ["pear", /grusz|(^|\s)pears?(\s|$)/],
  ["peach", /brzoskw|nektaryn|morel|śliw|peach|nectarine|apricot|(^|\s)plums?(\s|$)/],
  ["mango", /mango|papaj|marakuj|papaya|passion fruit/],
  ["pineapple", /ananas|pineapple/],
  ["coconut", /kokos|wiórk|coconut/],
  ["walnut", /włosk|pekan|walnut|pecan/],
  ["hazelnut", /lask|hazelnut/],
  ["pine-nuts", /piniow|pine nut/],
  ["nuts", /orzech|orzesz|nerkow|pistacj|makadami|bakali|(^|\s)nuts?(\s|$)|cashew|pistachio|macadamia/],
  ["sesame", /sezam|tahini|sesame/],
  ["poppy", /(^|\s)mak(u|iem)?(\s|$)|makow|poppy/],
  ["dill", /koper|(^|\s)dill/],
  ["rosemary", /rozmaryn|rosemary/],
  ["thyme", /tymian|cząber|majeran|oregano|lubczyk|estragon|zioł|thyme|marjoram|tarragon|(^|\s)herbs?(\s|$)/],
  ["mint", /mięt|melis|(^|\s)mint/],
  ["coriander", /kolendr|coriander|cilantro/],
  ["herbs", /bazyli|szałwi|pesto|liści|liść|basil|sage|leaves/],
  ["canned", /puszk|konserw|(^|\s)can(ned)?(\s|$)|tinned/],
  ["orange", /(^|\s)sok|juice/],
  ["ketchup", /(^|\s)sos|salsa|dressing|winegret|sauce|vinaigrette/],
  ["apple", /owoc|fruit/],
  ["water", /herbat|(^|\s)tea(\s|$)/],
];

export function ingredientIcon(name: string): IngredientIcon {
  const text = name.normalize("NFC").toLowerCase();
  return rules.find(([, pattern]) => pattern.test(text))?.[0] ?? "bowl";
}

export function ingredientIconIndex(name: string) {
  return ingredientIcons.indexOf(ingredientIcon(name));
}
