import type { Recipe } from "./recipe";
import data from "./popular-recipes.json";

// Generated by scripts/ingest-popular.mjs from data/popular-videos.json with the app's own Gemini pipeline.
export type PopularCategory = "sniadania" | "obiady" | "zupy" | "wege" | "makarony" | "azjatyckie" | "desery" | "wypieki";
export type PopularRecipe = {
  id: string; category: PopularCategory; dish: string; videoTitle: string; author: string; ingestedAt: string; recipe: Recipe;
  thumb?: "maxresdefault" | "hq720" | "sddefault" | "hqdefault";
  translations?: { en?: Recipe };
};

export const popularRecipes = data as PopularRecipe[];
export const popularCategories: { key: PopularCategory; label: string }[] = [
  { key: "sniadania", label: "Śniadania" }, { key: "obiady", label: "Obiady" }, { key: "zupy", label: "Zupy" }, { key: "wege", label: "Wege" },
  { key: "makarony", label: "Makarony" }, { key: "azjatyckie", label: "Azjatyckie" }, { key: "desery", label: "Desery" }, { key: "wypieki", label: "Wypieki" },
];
export const findPopular = (id: string) => popularRecipes.find(entry => entry.id === id) ?? null;
